HAI 1.2
I HAS A VAR
VAR R 1
IM IN YR FIZZBUZZ UPPIN YR VAR WILE BOTH SAEM VAR AN SMALLR OF VAR AN 100
    NOT MOD OF VAR AN 15 
    O RLY? 
        YA RLY, VISIBLE "FIZZBUZZ"
        MEBBE NOT MOD OF VAR AN 3, VISIBLE "FIZZ"
        MEBBE NOT MOD OF VAR AN 5, VISIBLE "BUZZ"
        NO WAI, VISIBLE VAR
    OIC
IM OUTTA YR FIZZBUZZ
KTHXBYE
